### ISSUE TITLE
Optimisations may affect validity when enabling multiple mutants

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#109]
When enabling multiple mutants on the optimized output from Dredd, there is a possibility that we may loose mutations that could be useful .

For example, in the expression `int x = 0 + 5`  we wouldn't replace the `+` with `*` because it's equivalent to replacing the entire binary expression with 0. But if we also enable the mutant that replaces 0 with another constant then replacement with `*` would be useful.

**Comment by afd** [comment]
This would be an issue if we were concerned with killing higher order mutants.

However, the reason for having the ability to enable multiple mutants in Dredd is to allow us to quickly detect when a test case kills *some* vs. *none* of a set of mutants, and for that use case this isn't a problem. Therefore I'll close this.
