### ISSUE TITLE
Negative constant replacement being implicitly cast to unsigned int

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#115]
The expression `unsigned int x = !0;` gets replaced by the mutated version:
`unsigned int x = __dredd_replace_expr_unsigned_int(__dredd_replace_expr_int(__dredd_replace_unary_operator_LNot_int_zero(__dredd_replace_expr_int(0, 0), 5), 7), 12);`

`__dredd_replace_expr_int()` can replace the expression with the constant `-1`, but since `__dredd_replace_expr_unsigned_int()` takes in an `unsigned int`, the `-1` will be implicitly cast to an `unsigned int`. This behavior is likely undesirable.

**Comment by afd** [comment]
I think there are pros and cons of both ways, and on balance I'm OK with this as is.

**Comment by afd** [comment]
Actually I wanna think about this more, so reopening.
