### ISSUE TITLE
Binary and unary operator replacement should take account of floating-point constants

### ISSUE THREAD

**Issue by afd** [mc-imperial/dredd#132]
Reviewing #128, which appears to handle the floating-point case, made me realise that we should take account of floating point constants when considering unary and binary expressions.

**Comment by afd** [comment]
@JamesLee-Jones - I had meant to mention you.

**Comment by JamesLee-Jones** [comment]
@afd Hopefully this should be a pretty easy fix. I also stumbled across this because I was getting name clashes from the binary expression mutation functions.
