### ISSUE TITLE
Segfault in member initializer list of class template

### ISSUE THREAD

**Issue by james-perretta** [mc-imperial/dredd#176]
Greetings, and thanks for telling me about this tool at ICST, Alastair! I was trying it out with a linked-list assignment and ran into a segfault. Here is a reduced version of the code that causes it:

```
template <typename T>
class List {
public:
  struct Node {
  };

  List() : node_ptr(0) {}

  Node *node_ptr; 
};
```

The segfault disappears if I make any of the following changes:
- Removing the member initializer list of the constructor (the segfault seems to be happening when attempting to inspect/mutate the `0` in the member initializer)
- Removing `template <typename T>`
- Moving the Node struct outside of the List class
- Changing the type of node_ptr from `Node*` to `int`

I'm using the pre-compiled Ubuntu 20.04 version. Please let me know if there's any additional information I can provide.

Thanks!
James

**Comment by afd** [comment]
Thanks James!

I tried this on the latest version built from source, and it seems to work:

```
./temp/build-Debug/src/dredd/dredd fromjames.cpp --mutation-info-file blah.json
```

This leads to the attached output file (which I had to rename to .txt).

[fromjames.cpp.txt](https://github.com/mc-imperial/dredd/files/11397303/fromjames.cpp.txt)

I'll look into doing another release and will see whether there's crash with the released version.

**Comment by afd** [comment]
OK, I have done another release - I only have things configured to release for Ubuntu 22.04 at the moment. Will that work for you? (Not sure what happens when you run an Ubuntu X application on Ubuntu Y < X when X and Y are still close.

I can certainly look into supporting 20.04 if you're keen to try dredd and would prefer that.

**Comment by james-perretta** [comment]
Super, thanks! The new release doesn't seem to work out of the box on Ubuntu 20.04 (it's missing a particular version of glibc/glibcxx), but I can just upgrade to 22.04. I'll let you know if I run into any other problems after upgrading.

**Comment by james-perretta** [comment]
I upgraded to Ubuntu 22.04, and it works as expected. Thanks!

**Comment by afd** [comment]
Great, thanks @james-perretta! Do open new issues if you run into any further problems, or have feature requests relating to your interests.
