### ISSUE TITLE
Install cmake-format in dev_shell.sh.template

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#180]
It appears that `cmake-format` is not installed by `dev_shell.sh.template` which causes the `scripts/check_format.sh` script to fail.

**Comment by afd** [comment]
The trouble is that cmake-format is a Python dependency, and at the moment the devshell template does't install any Python dependencies. Python can be rather fiddly - installing things with pip can work differently depending on what else you have installed, e.g. a Python virtual environment or whatever. So perhaps it's best if we address this by:

- documenting in the developer instructions that a prerequisite is having Python available and the cmake-format package of Python installed

- having the `check_format.sh` script start by issuing something like `cmake_format --version` and checking that this returns a non-zero error code. If it returns a non-zero error code a warning could be emitted that cmake format is not installed and then either check_format could error out, or instead formatting of CMake files could be skipped. (I'd be OK with the latter on the basis that this will be checked as part of CI, and it's not that common to modify CMake files.)

**Comment by JamesLee-Jones** [comment]
I prefer the idea of a non-zero exit code, just so we cover the unlikely case that `cmake_format` fails to install on CI in future and we miss it.

**Comment by afd** [comment]
Good point.

You happy to take this one?

**Comment by JamesLee-Jones** [comment]
> Good point.
> 
> You happy to take this one?

Yeah! There is a pull request up now.
