### ISSUE TITLE
Error writing JSON data when input file is large

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#192]
When applying Dredd to a very large source file (one generated by CSmith for example), calling `MessageToJsonString` in `main.cc` results in the following json generation status:
```
INVALID_ARGUMENT:Message too deep. Max recursion depth reached for type 'dredd.protobufs.SourceLocation', field 'start'
```
This is currently hidden as the only error returned is "Error writing JSON data to {filename}".

We should make the error messages clearer for cases that are expected to error, and should either limit the input size to prevent this happening or find a way to output the json anyway.

**Comment by JamesLee-Jones** [comment]
> What's the motivation for applying Dredd to Csmith-generated files? Testing of Dredd itseslf?

Yeah, the idea was to quickly check Dredd in a couple of ways, both the main branch and the stuff I've been working on. I thought it would be a quick way to see if we missed anything along similar lines to null pointer assignment (which fortunately didn't seem to turn up any errors in my quick testing). I also thought it would be good for checking we maintain semantic equivalence when applying mutations since the CSmith programs return a checksum, this did seem to be the case for the modified programs that terminated. However, there seemed to be a large number of outputs (almost all of the outputs for the modifications I have made which indicates something is likely wrong) that ran for long enough that I couldn't tell if it was going to terminate, I can imagine how this could be the case for some of the CSmith generated programs when they are mutated but may still be worth a little look.

> I'm OK with a failure to emit JSON for suitably deeply-nested files. I agree that if a clearer error message could be given then that would be good, so feel free to look into how to do that. But I don't think we need to find a way to overcome the depth limits of protobufs for this use case, since the real-world systems to which we'd like to apply Dredd won't have such deeply-nested expressions.

I agree, I'll look into making the error messages clearer.

**Comment by afd** [comment]
Perhaps --mutation-info-file should be made an optional argument, such that when it is not supplied, the mutation tree is not built. That would support this use case, and I was thinking about it anyway as it's a bit of a pain having to always provide that argument when you're merely debugging.

**Comment by JamesLee-Jones** [comment]
That would be a good idea. In the sort term I solved it by commenting out the JSON emission code because building the tree is fine, but it errors when writing to the JSON file, this approach would save the overhead of building it in the first place though.

**Comment by JamesLee-Jones** [comment]
We should also add a test case in C apps integration test to check that the program mutates fine when not passing mutation info file, but when trying to generate it the correct error message is printed.

**Comment by JamesLee-Jones** [comment]
It turns out it is important to be able to output large json files when applying Dredd to many source files within a project (mutating all of the the files under src in tint for example). The json is necessary when trying to figure out which mutants have been killed by an input.

**Comment by JamesLee-Jones** [comment]
It seems like the recursion limit is hardcoded in protobufs with no way to change it other than the source code. It is still possible to serialize the protobuf object to a binary string and write that to a file. It seems like there are two obvious options:

1. Write the mutation info to a file as a protobufs serialization and then read it anywhere else it's needed (mostly python scripts at the moment) using the same protobufs format. This seems like the logical choice since that's what is intended anyway.
2. We could write something to manually write the protobufs object out to a JSON to avoid the recursion limit. 

What do you think @afd?

**Comment by JamesLee-Jones** [comment]
Since I need to be able to read large mutation info files for my project, I updated #195 to include what this may look like.

**Comment by JamesLee-Jones** [comment]
The recursion limit is turning out to be a pretty big issue. It appears that support for increasing it is fragmented in the different protobufs implementations. For example, it is possible to increase the recursion depth using a [`CodedInputStream`](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.io.coded_stream/) when reading a message from a file in C++ but it doesn't seem to be possible to do this when trying to read a message in python. Since the aim of Dredd is to allow mutation testing of large C and C++ code bases, this definitely feels like something we should address.

It seems like it may be necessary to restructure the protobufs messages or switch away from it.

**Comment by afd** [comment]
As discussed when we met it would be great to get an example file where this is an issue - one of the files from tint.

**Comment by JamesLee-Jones** [comment]
The following is the file from tint that causes the recursion depth to be reached when writing out the mutation info file:
https://dawn.googlesource.com/tint/+/refs/heads/main/src/tint/lang/wgsl/reader/parser/parser.cc

It seems to be lines 92-126 that are causing the error:
```c++
bool is_reserved(const Token& t) {
    auto s = t.to_str_view();
    return s == "NULL" || s == "Self" || s == "abstract" || s == "active" || s == "alignas" ||
           s == "alignof" || s == "as" || s == "asm" || s == "asm_fragment" || s == "async" ||
           s == "attribute" || s == "auto" || s == "await" || s == "become" ||
           s == "binding_array" || s == "cast" || s == "catch" || s == "class" || s == "co_await" ||
           s == "co_return" || s == "co_yield" || s == "coherent" || s == "column_major" ||
           s == "common" || s == "compile" || s == "compile_fragment" || s == "concept" ||
           s == "const_cast" || s == "consteval" || s == "constexpr" || s == "constinit" ||
           s == "crate" || s == "debugger" || s == "decltype" || s == "delete" || s == "demote" ||
           s == "demote_to_helper" || s == "do" || s == "dynamic_cast" || s == "enum" ||
           s == "explicit" || s == "export" || s == "extends" || s == "extern" || s == "external" ||
           s == "filter" || s == "final" || s == "finally" || s == "friend" || s == "from" ||
           s == "fxgroup" || s == "get" || s == "goto" || s == "groupshared" || s == "highp" ||
           s == "impl" || s == "implements" || s == "import" || s == "inline" ||
           s == "instanceof" || s == "interface" || s == "layout" || s == "lowp" || s == "macro" ||
           s == "macro_rules" || s == "match" || s == "mediump" || s == "meta" || s == "mod" ||
           s == "module" || s == "move" || s == "mut" || s == "mutable" || s == "namespace" ||
           s == "new" || s == "nil" || s == "noexcept" || s == "noinline" ||
           s == "nointerpolation" || s == "noperspective" || s == "null" || s == "nullptr" ||
           s == "of" || s == "operator" || s == "package" || s == "packoffset" ||
           s == "partition" || s == "pass" || s == "patch" || s == "pixelfragment" ||
           s == "precise" || s == "precision" || s == "premerge" || s == "priv" ||
           s == "protected" || s == "pub" || s == "public" || s == "readonly" || s == "ref" ||
           s == "regardless" || s == "register" || s == "reinterpret_cast" || s == "require" ||
           s == "resource" || s == "restrict" || s == "self" || s == "set" || s == "shared" ||
           s == "sizeof" || s == "smooth" || s == "snorm" || s == "static" ||
           s == "static_assert" || s == "static_cast" || s == "std" || s == "subroutine" ||
           s == "super" || s == "target" || s == "template" || s == "this" || s == "thread_local" ||
           s == "throw" || s == "trait" || s == "try" || s == "type" || s == "typedef" ||
           s == "typeid" || s == "typename" || s == "typeof" || s == "union" || s == "unless" ||
           s == "unorm" || s == "unsafe" || s == "unsized" || s == "use" || s == "using" ||
           s == "varying" || s == "virtual" || s == "volatile" || s == "wgsl" || s == "where" ||
           s == "with" || s == "writeonly" || s == "yield";
}
```

**Comment by JamesLee-Jones** [comment]
It turns out this is not uncommon in real world projects, it also happens when applying Dredd to [source/opt/optimizer.cpp](https://github.com/KhronosGroup/SPIRV-Tools/blob/main/source/opt/optimizer.cpp) in spirv-opt.

**Comment by JamesLee-Jones** [comment]
After looking, I don't believe there is a compile time option to raise the recursion limit (which seems like a bit of an oversight). Most of the protobuf functions for parsing JSONs have an option for recursion limit, so this is of less concern. The variable that contains the limit we hit when writing out a JSON is [line 317 in protobuf/util/internal/protostream_objectsource.h](https://chromium.googlesource.com/chromium/src/third_party/+/refs/heads/main/protobuf/src/google/protobuf/util/internal/protostream_objectsource.h) as this class is used in BinaryToJsonStream ([Line 95-115 in protobuf/util/json_util.cc](https://chromium.googlesource.com/chromium/src/third_party/+/refs/heads/main/protobuf/src/google/protobuf/util/json_util.cc)). The class linked does contain a function to increase the recursion limit on lines 135-137 but is not static.

One option would be to modify BinaryToJsonStream to call `set_max_recursion_depth` on `proto_source`, but this feels like something that should already be possible in protobufs. I might open a pull request in the protobfus repo to add an option to the function call to allow this.

**Comment by JamesLee-Jones** [comment]
@afd @JonathanFoo0523 To continue the conversation from #258, I got a reply on my issue in the protobuf repo ([here](https://github.com/protocolbuffers/protobuf/issues/17218)) so will implement it when I have a spare minute and should act as a fix if we want to stick with protobufs. One downside I see to this is that it's possible that some of the other protobufs apis may not have the functionality to increase recursion depth when reading in the mutation tree (I believe python does).

**Comment by afd** [comment]
Thanks @JamesLee-Jones. Another possibility is for us to restructure the way we do protos, but it would be nice to be able to avoid that if possible.
