### ISSUE TITLE
Conflicting types for __dredd_replace_binary_operator_LAnd_long_long_long_rhs

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#196]
When we have a `long long` one one side of a logical and a `long` on the other side, then the opposite later (`long` on the left, `long long` on the right), we end up with conflicting types for `__dredd_replace_binary_operator_LAnd_long_long_long_rhs` and `__dredd_replace_binary_operator_LAnd_long_long_long_lhs`.

This can be reproduced by applying Dredd to the following without optimizations and compiling:
```
int main() {
    5LL && 4L;
    4L && 5LL;
}
```
The above example isn't valid in C++.

**Comment by afd** [comment]
Wow!! 🤣

**Comment by afd** [comment]
I suppose we could deal with this by inserting something in the name to indicate going from one argument to the next. Or alternatively by prefixing the LHS type on the name with 1_ and the RHS type with 2_

**Comment by JamesLee-Jones** [comment]
> I suppose we could deal with this by inserting something in the name to indicate going from one argument to the next. Or alternatively by prefixing the LHS type on the name with 1_ and the RHS type with 2_

That would work, we could go with arg1_..._arg2_... for clarity.

**Comment by afd** [comment]
Sounds good. Are you happy to do a PR for this, adding a test exposing the issue?
