### ISSUE TITLE
Consider adding multi-threading support for Dredd

### ISSUE THREAD

**Issue by JamesLee-Jones** [mc-imperial/dredd#232]
Currently Dredd can only run on a single thread. This is fine for smaller applications, but when mutating large applications (such as [tint](https://dawn.googlesource.com/tint)), this can take tens of minutes. Adding file level multi-threading to Dredd would allow for a substantial performance increase when mutating large projects.

**Comment by afd** [comment]
I am not convinced we want to go here. I think there are optimisations that could be done to make Dredd a bit faster, but the bottleneck of a mutation testing campaign isn't doing the one-off mutation. Rather, it is killing all the mutants.

**Comment by afd** [comment]
As we have now had success running Dredd on some pretty big projects, I'm going to close this.
