### ISSUE TITLE
Mutation of expression used in initializer list results in ill-formed program 

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#270]
Applying Dredd to
```
#include <initializer_list>
#include <cstdint>

template <typename T> class foo {
public:
  foo(std::initializer_list<T>) {}
};

int main() { 
    foo<uint64_t>{+2}; 
}
```
change the sole statement in `main()` to 
```
if (!__dredd_enabled_mutation(5)) { foo<uint64_t>{+__dredd_replace_expr_int_constant(2, 0)}; } 
```

This causes the following compilation error:
```
non-constant-expression cannot be narrowed from type 'int' to 'unsigned long' in initializer list
```

**Comment by JonathanFoo0523** [comment]
Note that `+` in `+2` is required to replicate the issue. Otherwise, Dredd will not mutate the expression `2`, and thus avoid this issue.

**Comment by JonathanFoo0523** [comment]
While we can reduce this bug by avoiding mutation of expression in such case, I think this approach will further reduce the number of mutants.

Is it possible to change the prelude function to a templated version
```
template <typename T> 
static T __dredd_replace_expr_int_constant(T arg, int local_mutation_id) {
  if (!__dredd_some_mutation_enabled) return arg;
  if (__dredd_enabled_mutation(local_mutation_id + 0)) return ~(arg);
  if (__dredd_enabled_mutation(local_mutation_id + 1)) return -(arg);
  if (__dredd_enabled_mutation(local_mutation_id + 2)) return 0;
  if (__dredd_enabled_mutation(local_mutation_id + 3)) return 1;
  if (__dredd_enabled_mutation(local_mutation_id + 4)) return -1;
  return arg;
}
```
and mutate the fault-causing expression to:
```
+__dredd_replace_expr_int_constant<uint64_t>(2, 0)
```

**Comment by afd** [comment]
I am worried that having templated mutator functions may end up getting very complicated and leading to unexpected issues. On the other hand, it might actually turn out to provide a simple and elegant solution to certain issues. @JonathanFoo0523 can you experiment with the template idea?

If it turns out to be non-trivial then I would prefer to work around this by detecting the special case and avoiding a mutation in that special case, and opening a "stretch goal" issue to consider a better solution in the longer term.

**Comment by JonathanFoo0523** [comment]
A slightly simpler example
```
#include <initializer_list>

class foo {
public:
  foo(std::initializer_list<unsigned int>) {}
};

int main() { 
    foo{+2}; 
}
```

**Comment by JonathanFoo0523** [comment]
The reason that dredd mutate `{+2}` but not `{2}` is because of the optimisation [here](https://github.com/mc-imperial/dredd/blob/776912deb92055f0aad9fa28156ace6b3b201cd1/src/libdredd/src/mutate_visitor.cc#L443). This optimisation check whether the current expression is a child of `CastExpr`. If so, we don't mutate the expression.

The AST generate for `{+2}` is of the form
```
`MaterializeTemporaryExpr 0x55d7abea7af8 <col:8, col:11> 'const unsigned int[1]' xvalue
  `-InitListExpr 0x55d7abea6e68 <col:8, col:11> 'const unsigned int[1]'
    `-ImplicitCastExpr 0x55d7abea7ae0 <col:9, col:10> 'const unsigned int' <IntegralCast>
      `-UnaryOperator 0x55d7abea6990 <col:9, col:10> 'int' prefix '+' cannot overflow
         `-IntegerLiteral 0x55d7abea6970 <col:10> 'int' 2
```
This `2` is still mutated because of the intermediate parent `UnaryOperator`.

@afd I believe this is a missed optimisation opportunity, right?

**Comment by JonathanFoo0523** [comment]
Another Example:
```
struct a {
  short b;
};
a c() { return {6 * 4}; }
```
