### ISSUE TITLE
Dredd mutate expression in `__builtin_frame_address()`

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#289]
Dredd mutates the `__builtin_frame_address()` in 
```
void foo() {
    __builtin_frame_address(0);
}
```
to
```
__builtin_frame_address(__dredd_replace_expr_unsigned_int_zero(0, 0));
```
leading to compilation error:
```
argument to '__builtin_frame_address' must be a constant integer
```

**Comment by JonathanFoo0523** [comment]
Avoiding mutation inside `__builtin_frame_address()` is not sufficient. Here's another example:
```
void foo() {
    const int x = 0;
    __builtin_frame_address(x);
}
```
compiles.

But the following doesn't:
```
void foo() {
    const int x = __dredd_replace_expr_int_zero(0, 0);
    if (!__dredd_enabled_mutation(4)) { __builtin_frame_address(x); }
}
```
with the same compilation error as previous.

**Comment by JonathanFoo0523** [comment]
We probably need some kind of rewriting as done by #273

**Comment by afd** [comment]
@JonathanFoo0523 Feel free to have a go at fixing this via rewriting, as per #273 - though please see #287 first, which changes the approach of #273 a bit. If you can review #287 then we can get it merged.

**Comment by JonathanFoo0523** [comment]
It seems that not all `__builtin_func()` calls require the argument to be a constant integer. However, we don't have an easy way to check if a function argument must be a constant integer (at least to my knowledge).

@afd, is it okay to specifically check for the `__builtin_frame_address()` function call and replace its expression? We might encounter other `__builtin_func()` calls that require a constant integer in the future.
