### ISSUE TITLE
Dredd mutator function hides declarations in namespace

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#296]
Given files `include.h`
```
namespace baz {
namespace bar {
bool foo(short x);

enum : short {B = 1};
}
}
```
and file `main.cc`:
```
#include "include.h"

using namespace baz;

void func() {
    foo(bar::B);
}
```

Note that `main.cc` compile successfully, even though `foo` is not explicitly stated with namespace `bar::foo`. However, applying dredd to `main.cc` changes the sole statement to
```
if (!__dredd_enabled_mutation(3)) { foo(__dredd_replace_expr_short_one(bar::B, 0)); }
```
and results in compilation error:
```
error: use of undeclared identifier 'foo'
```

**Comment by JonathanFoo0523** [comment]
Related info: [Koenig lookup](https://en.wikipedia.org/wiki/Argument-dependent_name_lookup)

**Comment by afd** [comment]
Perhaps this could be used to provide a work around and avoid mutating calls that use argument dependent lookup?

https://clang.llvm.org/doxygen/classclang_1_1CallExpr.html#a16460619f757c5a63ca6b80999d768cd

**Comment by JonathanFoo0523** [comment]
I am wondering whether enhancement proposed in #282 could be used as a workaround without reducing the number of mutants. For example,
```
namespace bar {
  void foo(int x);
  enum {B = 1};
}

int main()
  foo(bar::B);
}
```
we can have mutator function
```
template <typename T>
static T __dredd_replace_expr_int_one_like(T arg, int local_mutation_id) {
  if (!__dredd_some_mutation_enabled) return arg;
  if (__dredd_enabled_mutation(local_mutation_id + 0)) return static_cast<T>(~(arg));
  if (__dredd_enabled_mutation(local_mutation_id + 1)) return static_cast<T>(0);
  if (__dredd_enabled_mutation(local_mutation_id + 2)) return static_cast<T>(-1);
  return arg;
}
```
and the expression in `main()` become
```
foo(__dredd_replace_expr_int_one_like<decltype(bar::B)>(bar::B, 0));
```
