### ISSUE TITLE
Query mutant info not working properly for multi-line statements

### ISSUE THREAD

**Issue by afd** [mc-imperial/dredd#308]
Showing info for mutant 138 of the math example (a for loop) doesn't work at present.

**Comment by JonathanFoo0523** [comment]
Seems like it work for me? The output is:
```
Remove statement at math/src/exp.cc, 55:3--57:4

This is the removed statement:

  for (int i = 0; i < Mod(exp); ++i) {
  }
```

**Comment by afd** [comment]
The problem is that the body of the loop is not shown (but should be). I'll fix in due course.
