### ISSUE TITLE
Do not remove unary operators that are self-inverse

### ISSUE THREAD

**Issue by afd** [mc-imperial/dredd#97]
It's not clear from the code whether we consider replacing a unary operator with its argument - this should be checked.

**Comment by afd** [comment]
It looks like we don't do this.

It seems to me that it is worth removing increment / decrement operators, so:

* `++x` -> `x`
* `--x` -> `x`
* `x++` -> `x`
* `x--` -> `x`

It seems that it's *not* worth removing `!`, `-` and `~`, because they are self inverses, so removing has the same affect as applying, and we will perform the application via `MutationReplaceExpr` - so as an optimisation we should omit these.

@JamesLee-Jones does this make sense to you?

**Comment by JamesLee-Jones** [comment]
@afd Yeah, that makes sense. Regarding the operators that are self-inverse, do you mean that we should still remove them when optimisations are disabled or just generally never remove them regardless of the optimisation flag?

**Comment by afd** [comment]
I've been umming and ahing about that, and I think we should remove them when optimisations are disabled, for completeness. For similar reasons, I put the code that skips paren expressions under the optimisation flag.

Can I add this issue to your TODO list?

**Comment by JamesLee-Jones** [comment]
That would make sense. 

Yeah sure.

**Comment by afd** [comment]
Aside: I'm now wondering whether something along these lines *is* already happening, as I just came across:

```
static float __dredd_replace_unary_operator_Minus_float_one(float arg, int local_mutation_id) {
  if (!__dredd_some_mutation_enabled) return -arg;
  if (__dredd_enabled_mutation(local_mutation_id + 0)) return arg;
  return -arg;
}
```
It looks like the `return arg` case is doing the job here. Anyway, would be great if you could check carefully in due course - I think I've done too much Dredd for today so am gonna stop!

**Comment by afd** [comment]
I have renamed the issue to just focus on the self-inverse case. If you could take care of that, @JamesLee-Jones, I'll look at the ++, -- cases.
